name: Build and Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to ECR
      - name: Log in to ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: docker build -t 847837762102.dkr.ecr.us-west-2.amazonaws.com/dotnet-api:${{ github.sha }} .

      # Step 4: Push Docker Image
      - name: Push Docker Image
        run: docker push 847837762102.dkr.ecr.us-west-2.amazonaws.com/dotnet-api:${{ github.sha }}

  deploy-lambda:
    name: Update Lambda Function
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # Step 1: Checkout Terraform Code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: https://github.com/lhf552004/InventoryManagementInfrastructure
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 3: Run Terraform Apply
      - name: Deploy Lambda
        run: terraform apply -auto-approve -var "image_tag=${{ github.sha }}"
